/* la station */
INSERT INTO resort( name,active ) values( 'Villars-Gryon','Y' );

/* les installations */
INSERT INTO lift( id,name,type ) values
	( 1,'BVB Villars - Bretaye','Train' ),
	( 2,"TC8 Villars - Roc d'Orsay",'Télécabine' ),
	( 3,'Grand Chamossaire','Télésiège 6 places' ),
	( 4,'Bretaye - Orsay','Téléski' ),
	( 5,"Combe d'Orsay",'Téléski' ),
	( 6,'Lac Noir - Chaux Ronde','Télésiège 4 places' ),
	( 7,'Lac Noir - Bretaye','Téléski' ),
	( 8,'Lac de Bretaye','Téléski' ),
	( 9,'Chaux Ronde I','Téléski' ),
	( 10,'Chaux Ronde II','Téléski' ),
	( 11,'Petit Chamossaire','Télésiège 6 places' ),
	( 12,'Rasse - Chaux Ronde','Télésiège 6 places' ),
	( 13,'Palace','Téléski' ),
	( 14,'Chavonnes','Téléski' ),
	( 15,'TC4 Barboleuse - Les Chaux','Télécabine' ),
	( 16,'Sodoleuvre - La Croix','Télésiège 4 places' ),
	( 17,'Gryonne','Téléski' ),
	( 18,'Plan - Métroz','Téléski' ),
	( 19,'Fracherets','Téléski' )
;

/* les pistes */
INSERT INTO piste( id,name,rating ) values
	( 1,'Ruvines','Advanced' ),
	( 2,'La Croix noire','Advanced' ),
	( 3,'Chamois','Intermediate' ),
	( 4,'Aigle','Intermediate' ),
	( 5,'Chamossaire - Nord','Intermediate' ),
	( 6,'Chamossaire - Sud','Intermediate' ),
	( 7,'Satde','Intermediate' ),
	( 8,'Chaux Ronde Rouge','Intermediate' ),
	( 9,'Les Oeils','Intermediate' ),
	( 10,'Les Vernes','Intermediate' ),
	( 11,'La Traverse','Intermediate' ),
	( 12,'Golette','Intermediate' ),
	( 13,"Combe d'Orsay",'Intermediate' ),
	( 14,'Sodoleuvre Rouge','Intermediate' ),
	( 15,'Cuelle','Intermediate' ),
	( 16,'Leuins Rouge (Frach.)','Intermediate' ),
	( 17,'La Croix rouge','Intermediate' ),
	( 18,'Bouquetins (Roc - Villars)','Off-piste' ),
	( 19,'Loveresse (Col de Soud - gare)','Off-piste' ),
	( 20,'Le Crot','Off-piste' ),
	( 21,'Monjoie (Eurotel)','Off-piste' ),
	( 22,'Parc','Off-piste' ),
	( 23,'Leuins Jaune (Frience)','Off-piste' ),
	( 24,'Bretaye - Orsay','Easy' ),
	( 25,'Lac de Bretaye','Easy' ),
	( 26,'Lac Noir','Easy' ),
	( 27,'Chaux Ronde Bleue','Easy' ),
	( 28,'La Rasse','Easy' ),
	( 29,'Populaire Bretaye - Col de Soud','Easy' ),
	( 30,'Lapins (Col de Soud - télécabine)','Easy' ),
	( 31,NULL,'Easy' ),
	( 32,'Gryonne','Easy' ),
	( 33,'Sodoleuvre Bleue','Easy' ),
	( 34,'Populaire Gryon','Easy' ),
	( 35,'Fracherets','Easy' )
;

UPDATE piste SET lifts = '6,9,10,12' WHERE id = 27;

INSERT INTO resort_item( resort_id,item_source,item_id ) values
	( 1,'lift',1 ),
	( 1,'lift',2 ),
	( 1,'lift',3 ),
	( 1,'lift',4 ),
	( 1,'lift',5 ),
	( 1,'lift',6 ),
	( 1,'lift',7 ),
	( 1,'lift',8 ),
	( 1,'lift',9 ),
	( 1,'lift',10 ),
	( 1,'lift',11 ),
	( 1,'lift',12 ),
	( 1,'lift',13 ),
	( 1,'lift',14 ),
	( 1,'lift',15 ),
	( 1,'lift',16 ),
	( 1,'lift',17 ),
	( 1,'lift',18 ),
	( 1,'lift',19 ),
	( 1,'piste',1 ),
	( 1,'piste',2 ),
	( 1,'piste',3 ),
	( 1,'piste',4 ),
	( 1,'piste',5 ),
	( 1,'piste',6 ),
	( 1,'piste',7 ),
	( 1,'piste',8 ),
	( 1,'piste',9 ),
	( 1,'piste',10 ),
	( 1,'piste',11 ),
	( 1,'piste',12 ),
	( 1,'piste',13 ),
	( 1,'piste',14 ),
	( 1,'piste',15 ),
	( 1,'piste',16 ),
	( 1,'piste',17 ),
	( 1,'piste',18 ),
	( 1,'piste',19 ),
	( 1,'piste',20 ),
	( 1,'piste',21 ),
	( 1,'piste',22 ),
	( 1,'piste',23 ),
	( 1,'piste',24 ),
	( 1,'piste',25 ),
	( 1,'piste',26 ),
	( 1,'piste',27 ),
	( 1,'piste',28 ),
	( 1,'piste',29 ),
	( 1,'piste',30 ),
	( 1,'piste',31 ),
	( 1,'piste',32 ),
	( 1,'piste',33 ),
	( 1,'piste',34 ),
	( 1,'piste',35 )
;
